In [1]:
import seaborn as sns

In [3]:
sns.get_dataset_names()

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'dowjones',
 'exercise',
 'flights',
 'fmri',
 'geyser',
 'glue',
 'healthexp',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'seaice',
 'taxis',
 'tips',
 'titanic']

In [4]:
df = sns.load_dataset('titanic')

In [5]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [6]:
df = df[['survived','pclass','fare']]

In [7]:
df.head()

   survived  pclass     fare
0         0       3   7.2500
1         1       1  71.2833
2         1       3   7.9250
3         1       1  53.1000
4         0       3   8.0500

In [8]:
df.shape

(891, 3)

In [10]:
y = df['survived']
X = df.drop(['survived'],axis=1)

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

In [11]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.33)

In [12]:
scaled = MinMaxScaler()

In [13]:
# By default MinMaxScaler has the scaling limit of 0-1, we can change it based on our requirements

In [14]:
X_train_scaled = scaled.fit_transform(X_train) # We will be training the scaler with the ttraining data and then will apply the same scaling to the testing data

In [15]:
X_train_scaled

array([[1.        , 0.01756683],
       [1.        , 0.05445717],
       [1.        , 0.        ],
       ...,
       [1.        , 0.01985208],
       [1.        , 0.01517579],
       [1.        , 0.01410226]])

In [16]:
X_test_scaled = scaled.transform(X_test)

In [17]:
X_test_scaled

array([[0.        , 0.05182215],
       [1.        , 0.04713766],
       [1.        , 0.02810693],
       [1.        , 0.04538098],
       [0.        , 0.20772777],
       [1.        , 0.01571255],
       [1.        , 0.13575256],
       [0.        , 0.21642979],
       [1.        , 0.03945217],
       [1.        , 0.01217479],
       [1.        , 0.01854277],
       [0.5       , 0.02537431],
       [0.        , 0.1561496 ],
       [0.5       , 0.02410559],
       [0.5       , 0.02635025],
       [1.        , 0.01546857],
       [0.5       , 0.08115719],
       [0.5       , 0.02537431],
       [1.        , 0.01541158],
       [1.        , 0.03513366],
       [1.        , 0.02822072],
       [0.        , 0.05182215],
       [1.        , 0.01517579],
       [1.        , 0.01521639],
       [0.        , 0.07729405],
       [0.5       , 0.02537431],
       [1.        , 0.07746484],
       [0.        , 0.2958059 ],
       [1.        , 0.03025399],
       [1.        , 0.02975782],
       [0.5       , 0.02049464],
       [0.        , 0.29953885],
       [0.        , 0.0541074 ],
       [0.        , 0.44409922],
       [1.        , 0.01517579],
       [1.        , 0.01338651],
       [0.5       , 0.02635025],
       [1.        , 0.01640391],
       [0.5       , 0.0585561 ],
       [1.        , 0.01541158],
       [1.        , 0.01756683],
       [1.        , 0.04970769],
       [0.        , 0.        ],
       [0.        , 0.05074862],
       [1.        , 0.01546857],
       [0.        , 0.16293235],
       [1.        , 0.01517579],
       [1.        , 0.01546857],
       [0.5       , 0.14346245],
       [0.        , 0.1756683 ],
       [0.        , 0.14976542],
       [1.        , 0.02434958],
       [1.        , 0.01541158],
       [0.5       , 0.05270049],
       [1.        , 0.01541158],
       [1.        , 0.03259623],
       [1.        , 0.01690807],
       [1.        , 0.01410226],
       [1.        , 0.01427305],
       [1.        , 0.01546857],
       [0.5       , 0.05074862],
       [1.        , 0.02618765],
       [0.5       , 0.02537431],
       [1.        , 0.02810693],
       [0.        , 0.10149724],
       [1.        , 0.01571255],
       [0.        , 0.06929139],
       [1.        , 0.06126432],
       [1.        , 0.01467962],
       [1.        , 0.02173075],
       [1.        , 0.03142511],
       [1.        , 0.01541158],
       [0.        , 0.06050797],
       [1.        , 0.01376068],
       [1.        , 0.0915427 ],
       [1.        , 0.01620052],
       [0.5       , 0.05074862],
       [1.        , 0.01521639],
       [1.        , 0.01376068],
       [1.        , 0.01854277],
       [1.        , 0.01546857],
       [1.        , 0.01546857],
       [1.        , 0.01920972],
       [0.        , 0.51334181],
       [0.        , 0.09193308],
       [0.        , 0.10149724],
       [0.5       , 0.02049464],
       [1.        , 0.0915427 ],
       [0.5       , 0.02049464],
       [1.        , 0.03513366],
       [1.        , 0.01854277],
       [0.        , 0.12097534],
       [0.5       , 0.05074862],
       [1.        , 0.0150944 ],
       [0.5       , 0.05270049],
       [0.5       , 0.02537431],
       [1.        , 0.01546857],
       [0.5       , 0.05123659],
       [1.        , 0.04577135],
       [0.        , 0.10149724],
       [1.        , 0.01920152],
       [0.        , 0.05797054],
       [1.        , 0.01415106],
       [0.        , 0.05130978],
       [1.        , 0.01512699],
       [0.        , 0.07729405],
       [1.        , 0.01411046],
       [0.5       , 0.0541074 ],
       [1.        , 0.11027246],
       [0.5       , 0.05074862],
       [1.        , 0.06126432],
       [0.5       , 0.04098927],
       [0.5       , 0.02830212],
       [0.5       , 0.02537431],
       [0.5       , 0.02049464],
       [1.        , 0.01546857],
       [0.        , 0.15546645],
       [1.        , 0.04970769],
       [0.        , 0.06929139],
       [0.5       , 0.02049464],
       [1.        , 0.05445717],
       [0.5       , 0.02342244],
       [1.        , 0.03025399],
       [1.        , 0.13575256],
       [1.        , 0.01546857],
       [1.        , 0.01690807],
       [0.        , 0.41250333],
       [0.        , 0.05182215],
       [0.        , 0.51334181],
       [1.        , 0.01541158],
       [0.        , 0.15085515],
       [0.        , 0.0975935 ],
       [1.        , 0.03025399],
       [0.5       , 0.02049464],
       [0.        , 0.05953204],
       [0.        , 0.48312843],
       [0.        , 0.11125659],
       [0.        , 1.        ],
       [0.        , 0.2342244 ],
       [1.        , 0.01510259],
       [1.        , 0.06104473],
       [0.5       , 0.02049464],
       [0.        , 0.06764049],
       [0.5       , 0.02537431],
       [0.        , 0.11125659],
       [1.        , 0.01541158],
       [0.        , 0.06640418],
       [1.        , 0.01533038],
       [1.        , 0.01646071],
       [0.5       , 0.02537431],
       [1.        , 0.0915427 ],
       [0.        , 0.09662576],
       [1.        , 0.01512699],
       [0.5       , 0.02537431],
       [0.5       , 0.04489301],
       [0.        , 0.05991421],
       [1.        , 0.04396587],
       [0.5       , 0.02537431],
       [0.5       , 0.02537431],
       [1.        , 0.0375897 ],
       [0.        , 0.51212189],
       [1.        , 0.01571255],
       [0.5       , 0.07612293],
       [1.        , 0.0239836 ],
       [1.        , 0.01533038],
       [1.        , 0.01632251],
       [1.        , 0.01541158],
       [0.        , 0.05604307],
       [1.        , 0.01512699],
       [1.        , 0.02947324],
       [0.        , 0.0585561 ],
       [0.        , 0.15546645],
       [0.5       , 0.05660423],
       [1.        , 0.01541158],
       [1.        , 0.01411046],
       [0.        , 0.15216447],
       [0.5       , 0.05123659],
       [0.5       , 0.05123659],
       [0.        , 0.15390495],
       [0.        , 0.28598956],
       [1.        , 0.01541158],
       [1.        , 0.0375897 ],
       [1.        , 0.01541158],
       [0.5       , 0.02537431],
       [0.5       , 0.0239592 ],
       [1.        , 0.04713766],
       [1.        , 0.05684821],
       [1.        , 0.03093714],
       [0.        , 0.05060223],
       [1.        , 0.13575256],
       [1.        , 0.01533038],
       [0.        , 0.13526459],
       [0.5       , 0.02244651],
       [1.        , 0.01415106],
       [1.        , 0.01571255],
       [1.        , 0.01849397],
       [0.        , 0.16231419],
       [0.5       , 0.05074862],
       [0.        , 0.11980422],
       [0.5       , 0.05869429],
       [0.5       , 0.04098927],
       [0.5       , 0.08115719],
       [1.        , 0.06104473],
       [1.        , 0.01410226],
       [1.        , 0.01411046],
       [0.5       , 0.04098927],
       [0.5       , 0.03659756],
       [1.        , 0.07746484],
       [1.        , 0.01517579],
       [1.        , 0.01571255],
       [0.5       , 0.04489301],
       [0.5       , 0.05074862],
       [0.5       , 0.02049464],
       [1.        , 0.06126432],
       [1.        , 0.01533038],
       [1.        , 0.01592394],
       [1.        , 0.03025399],
       [1.        , 0.02821272],
       [1.        , 0.01512699],
       [1.        , 0.01690807],
       [1.        , 0.01571255],
       [1.        , 0.01410226],
       [1.        , 0.01376068],
       [1.        , 0.03474329],
       [1.        , 0.07746484],
       [0.5       , 0.02691961],
       [1.        , 0.01541158],
       [1.        , 0.04970769],
       [1.        , 0.02434958],
       [1.        , 0.01571255],
       [0.        , 0.10257897],
       [0.5       , 0.02537431],
       [0.        , 0.1756683 ],
       [1.        , 0.04298994],
       [0.5       , 0.04098927],
       [1.        , 0.01571255],
       [1.        , 0.06709553],
       [1.        , 0.01537917],
       [0.5       , 0.04098927],
       [0.        , 0.13913574],
       [1.        , 0.05684821],
       [1.        , 0.01512699],
       [0.5       , 0.02936745],
       [1.        , 0.01571255],
       [1.        , 0.04113566],
       [1.        , 0.11027246],
       [0.        , 0.21255864],
       [0.        , 0.18249985],
       [1.        , 0.01694867],
       [1.        , 0.01493181],
       [1.        , 0.01512699],
       [1.        , 0.01571255],
       [1.        , 0.06709553],
       [0.5       , 0.        ],
       [0.        , 0.15390495],
       [0.        , 0.17777476],
       [0.5       , 0.02049464],
       [0.        , 0.17777476],
       [0.5       , 0.05074862],
       [1.        , 0.01512699],
       [1.        , 0.02975782],
       [0.        , 0.05182215],
       [1.        , 0.01375249],
       [0.5       , 0.02410559],
       [0.5       , 0.05416439],
       [0.5       , 0.14346245],
       [1.        , 0.02434958],
       [1.        , 0.02830212],
       [0.        , 0.06929139],
       [0.        , 0.1545881 ],
       [1.        , 0.01415106],
       [0.        , 0.05182215],
       [1.        , 0.01571255],
       [0.        , 0.44409922],
       [0.5       , 0.05074862],
       [0.        , 0.11594108],
       [1.        , 0.0436405 ],
       [0.        , 0.10735285],
       [0.        , 0.1036443 ],
       [1.        , 0.01541158],
       [1.        , 0.02173075],
       [1.        , 0.01546857],
       [0.5       , 0.02537431],
       [0.        , 0.12999454],
       [0.        , 1.        ],
       [0.5       , 0.05074862],
       [0.        , 0.26086743],
       [0.        , 0.063086  ],
       [1.        , 0.01571255],
       [1.        , 0.01376888],
       [0.5       , 0.02537431],
       [1.        , 0.03093714],
       [0.5       , 0.02537431],
       [1.        , 0.06104473],
       [0.        , 0.09662576]])

In [19]:
# In the next video we will be possibly discussing about correlation techniques